# Generated by Django 4.0.3 on 2022-04-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0002_alter_author_pic_alter_book_bookpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.ImageField(upload_to='author/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='category/%Y/%m/%d/'),
        ),
    ]
